sudo: false
language: node_js
node_js:
  - 'stable'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  # - npm update
  - npm install -g serverless
install:
  - npm install ci
  - sls dynamodb install
script:
  - sls dynamodb start --migrate --stage local & sleep 10 && npm run coveralls
after_success:
  - serverless deploy --stage test